-- Complete Database Setup for SecureServe MVP
-- Run this entire file in your Supabase SQL editor

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Freelancer Profiles Table
CREATE TABLE IF NOT EXISTS freelancer_profiles (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  freelancer_id VARCHAR(20) UNIQUE NOT NULL, -- System generated ID (e.g., F123456789)
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  mobile_number VARCHAR(20) NOT NULL,
  country_code VARCHAR(5) DEFAULT '+91',
  upi_id VARCHAR(100),
  aadhar_number VARCHAR(12),
  profile_completed BOOLEAN DEFAULT FALSE,
  profile_verified BOOLEAN DEFAULT FALSE,
  account_status VARCHAR(20) DEFAULT 'active' CHECK (account_status IN ('active', 'suspended', 'inactive')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Client Profiles Table
CREATE TABLE IF NOT EXISTS client_profiles (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  client_id VARCHAR(20) UNIQUE NOT NULL, -- System generated ID (e.g., C123456789)
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  mobile_number VARCHAR(20) NOT NULL,
  country_code VARCHAR(5) DEFAULT '+91',
  company_name VARCHAR(255),
  business_type VARCHAR(50),
  pan_tan_number VARCHAR(20),
  upi_id VARCHAR(100),
  profile_completed BOOLEAN DEFAULT FALSE,
  profile_verified BOOLEAN DEFAULT FALSE,
  account_status VARCHAR(20) DEFAULT 'active' CHECK (account_status IN ('active', 'suspended', 'inactive')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Projects Table (Skip creation - already exists with different schema)
-- Existing table has: id, project_id, client_id, freelancer_id, project_category, 
-- project_name, project_requirement, desired_completion_date, project_status, 
-- created_at, updated_at, project_status_workflow

-- Transactions Table (Updated with correct fields)
CREATE TABLE IF NOT EXISTS transactions (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  transaction_id VARCHAR(10) UNIQUE NOT NULL, -- 10 digit number autogenerated (1000000001, 1000000002...)
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
  transaction_value DECIMAL(10,2) NOT NULL, -- Currency with 8 digits and 2 decimals
  fee_from_client DECIMAL(10,2) NOT NULL, -- Auto calculated: 3.5% of transaction_value
  fee_from_freelancer DECIMAL(10,2) NOT NULL, -- Auto calculated: 3.5% of transaction_value
  freelancer_amount DECIMAL(10,2) NOT NULL, -- Auto calculated: 93% of transaction_value
  transaction_status VARCHAR(50) NOT NULL CHECK (transaction_status IN ('Project under Manual Review', 'Fund Secured', 'Successfully closed', 'Chargeback')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Messages Table (Updated with correct fields)
CREATE TABLE IF NOT EXISTS messages (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  message_id VARCHAR(3) UNIQUE NOT NULL, -- 3 digit number auto assigned (001, 002...)
  message_date_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(), -- System captured date value
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
  client_id UUID REFERENCES client_profiles(id),
  freelancer_id UUID REFERENCES freelancer_profiles(id),
  message_content VARCHAR(200) NOT NULL, -- 200 char single text line
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Function to generate transaction ID (10 digit incremental)
CREATE OR REPLACE FUNCTION generate_transaction_id()
RETURNS TRIGGER AS $$
DECLARE
  next_id INTEGER;
BEGIN
  -- Get the next transaction ID
  SELECT COALESCE(MAX(CAST(transaction_id AS INTEGER)), 1000000000) + 1
  INTO next_id
  FROM transactions;
  
  -- Set the transaction_id for the new record
  NEW.transaction_id := next_id::TEXT;
  
  -- Calculate fees and amounts
  NEW.fee_from_client := (NEW.transaction_value * 0.035);
  NEW.fee_from_freelancer := (NEW.transaction_value * 0.035);
  NEW.freelancer_amount := (NEW.transaction_value * 0.93);
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-generate transaction ID and calculate fees
DROP TRIGGER IF EXISTS trigger_generate_transaction_id ON transactions;
CREATE TRIGGER trigger_generate_transaction_id
  BEFORE INSERT ON transactions
  FOR EACH ROW
  EXECUTE FUNCTION generate_transaction_id();

-- Function to generate message ID (3 digit incremental)
CREATE OR REPLACE FUNCTION generate_message_id()
RETURNS TRIGGER AS $$
DECLARE
  next_id INTEGER;
BEGIN
  -- Get the next message ID
  SELECT COALESCE(MAX(CAST(message_id AS INTEGER)), 0) + 1
  INTO next_id
  FROM messages;
  
  -- Set the message_id for the new record (padded to 3 digits)
  NEW.message_id := LPAD(next_id::TEXT, 3, '0');
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-generate message ID
DROP TRIGGER IF EXISTS trigger_generate_message_id ON messages;
CREATE TRIGGER trigger_generate_message_id
  BEFORE INSERT ON messages
  FOR EACH ROW
  EXECUTE FUNCTION generate_message_id();

-- Enable Row Level Security (RLS)
ALTER TABLE freelancer_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (to avoid conflicts)
DROP POLICY IF EXISTS "Users can view own freelancer profile" ON freelancer_profiles;
DROP POLICY IF EXISTS "Users can update own freelancer profile" ON freelancer_profiles;
DROP POLICY IF EXISTS "Users can insert own freelancer profile" ON freelancer_profiles;

DROP POLICY IF EXISTS "Users can view own client profile" ON client_profiles;
DROP POLICY IF EXISTS "Users can update own client profile" ON client_profiles;
DROP POLICY IF EXISTS "Users can insert own client profile" ON client_profiles;

DROP POLICY IF EXISTS "Users can view projects they're involved in" ON projects;
DROP POLICY IF EXISTS "Clients can create projects" ON projects;
DROP POLICY IF EXISTS "Users can update projects they own" ON projects;

DROP POLICY IF EXISTS "Users can view their transactions" ON transactions;
DROP POLICY IF EXISTS "Users can create transactions for their projects" ON transactions;

DROP POLICY IF EXISTS "Users can view project messages" ON messages;
DROP POLICY IF EXISTS "Users can send messages to their projects" ON messages;

-- RLS Policies for Freelancer Profiles
CREATE POLICY "Users can view own freelancer profile" ON freelancer_profiles
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update own freelancer profile" ON freelancer_profiles
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own freelancer profile" ON freelancer_profiles
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- RLS Policies for Client Profiles
CREATE POLICY "Users can view own client profile" ON client_profiles
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update own client profile" ON client_profiles
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own client profile" ON client_profiles
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- RLS Policies for Projects (Updated for existing schema)
CREATE POLICY "Users can view projects they're involved in" ON projects
  FOR SELECT USING (
    auth.uid() IN (
      SELECT user_id FROM client_profiles WHERE id::UUID = projects.client_id::UUID
      UNION
      SELECT user_id FROM freelancer_profiles WHERE freelancer_id = projects.freelancer_id
    )
  );

CREATE POLICY "Clients can create projects" ON projects
  FOR INSERT WITH CHECK (
    auth.uid() IN (SELECT user_id FROM client_profiles WHERE id::UUID = projects.client_id::UUID)
  );

CREATE POLICY "Users can update projects they own" ON projects
  FOR UPDATE USING (
    auth.uid() IN (
      SELECT user_id FROM client_profiles WHERE id::UUID = projects.client_id::UUID
      UNION
      SELECT user_id FROM freelancer_profiles WHERE freelancer_id = projects.freelancer_id
    )
  );

-- RLS Policies for Transactions (Updated for existing projects schema)
-- Freelancers can only VIEW transactions, clients can VIEW and CREATE
CREATE POLICY "Users can view their transactions" ON transactions
  FOR SELECT USING (
    auth.uid() IN (
      SELECT cp.user_id FROM client_profiles cp 
      JOIN projects p ON p.client_id = cp.user_id 
      WHERE p.id::UUID = transactions.project_id::UUID
      UNION
      SELECT fp.user_id FROM freelancer_profiles fp 
      JOIN projects p ON p.freelancer_id = fp.freelancer_id 
      WHERE p.id::UUID = transactions.project_id::UUID
    )
  );

-- Only CLIENTS can create transactions (freelancers cannot create/modify)
CREATE POLICY "Clients can create transactions for their projects" ON transactions
  FOR INSERT WITH CHECK (
    auth.uid() IN (
      SELECT cp.user_id FROM client_profiles cp 
      JOIN projects p ON p.client_id = cp.user_id 
      WHERE p.id::UUID = transactions.project_id::UUID
    )
  );

-- Only CLIENTS can update transactions for their projects
CREATE POLICY "Clients can update transactions for their projects" ON transactions
  FOR UPDATE USING (
    auth.uid() IN (
      SELECT cp.user_id FROM client_profiles cp 
      JOIN projects p ON p.client_id = cp.user_id 
      WHERE p.id::UUID = transactions.project_id::UUID
    )
  );

-- RLS Policies for Messages
CREATE POLICY "Users can view project messages" ON messages
  FOR SELECT USING (
    auth.uid() IN (
      SELECT cp.user_id FROM client_profiles cp 
      WHERE cp.id::UUID = messages.client_id::UUID
      UNION
      SELECT fp.user_id FROM freelancer_profiles fp 
      WHERE fp.id::UUID = messages.freelancer_id::UUID
    )
  );

CREATE POLICY "Users can send messages to their projects" ON messages
  FOR INSERT WITH CHECK (
    auth.uid() IN (
      SELECT cp.user_id FROM client_profiles cp 
      WHERE cp.id::UUID = messages.client_id::UUID
      UNION
      SELECT fp.user_id FROM freelancer_profiles fp 
      WHERE fp.id::UUID = messages.freelancer_id::UUID
    )
  );

-- Functions for automatic profile creation
CREATE OR REPLACE FUNCTION handle_new_freelancer()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO freelancer_profiles (user_id, freelancer_id, email, full_name)
  VALUES (
    NEW.id, 
    'F' || LPAD(FLOOR(RANDOM() * 1000000000)::TEXT, 9, '0'),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', '')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION handle_new_client()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO client_profiles (user_id, client_id, email, full_name)
  VALUES (
    NEW.id, 
    'C' || LPAD(FLOOR(RANDOM() * 1000000000)::TEXT, 9, '0'),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', '')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop existing triggers if they exist
DROP TRIGGER IF EXISTS on_auth_user_created_freelancer ON auth.users;
DROP TRIGGER IF EXISTS on_auth_user_created_client ON auth.users;

-- Triggers for automatic profile creation
CREATE TRIGGER on_auth_user_created_freelancer
  AFTER INSERT ON auth.users
  FOR EACH ROW 
  WHEN (NEW.raw_user_meta_data->>'user_type' = 'freelancer')
  EXECUTE FUNCTION handle_new_freelancer();

CREATE TRIGGER on_auth_user_created_client
  AFTER INSERT ON auth.users
  FOR EACH ROW 
  WHEN (NEW.raw_user_meta_data->>'user_type' = 'client')
  EXECUTE FUNCTION handle_new_client();

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop existing triggers if they exist
DROP TRIGGER IF EXISTS update_freelancer_profiles_updated_at ON freelancer_profiles;
DROP TRIGGER IF EXISTS update_client_profiles_updated_at ON client_profiles;
DROP TRIGGER IF EXISTS update_projects_updated_at ON projects;

-- Triggers for updated_at
CREATE TRIGGER update_freelancer_profiles_updated_at
  BEFORE UPDATE ON freelancer_profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_client_profiles_updated_at
  BEFORE UPDATE ON client_profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_projects_updated_at
  BEFORE UPDATE ON projects
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Drop existing indexes if they exist
DROP INDEX IF EXISTS idx_freelancer_profiles_user_id;
DROP INDEX IF EXISTS idx_freelancer_profiles_freelancer_id;
DROP INDEX IF EXISTS idx_client_profiles_user_id;
DROP INDEX IF EXISTS idx_client_profiles_client_id;
DROP INDEX IF EXISTS idx_projects_client_id;
DROP INDEX IF EXISTS idx_projects_freelancer_id;
DROP INDEX IF EXISTS idx_projects_status;
DROP INDEX IF EXISTS idx_transactions_project_id;
DROP INDEX IF EXISTS idx_transactions_transaction_id;
DROP INDEX IF EXISTS idx_messages_project_id;
DROP INDEX IF EXISTS idx_messages_created_at;

-- Indexes for better performance (only create if columns exist)
DO $$
BEGIN
  -- Only create indexes if the tables and columns exist
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'freelancer_profiles') THEN
    CREATE INDEX IF NOT EXISTS idx_freelancer_profiles_user_id ON freelancer_profiles(user_id);
    CREATE INDEX IF NOT EXISTS idx_freelancer_profiles_freelancer_id ON freelancer_profiles(freelancer_id);
  END IF;
  
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'client_profiles') THEN
    CREATE INDEX IF NOT EXISTS idx_client_profiles_user_id ON client_profiles(user_id);
    CREATE INDEX IF NOT EXISTS idx_client_profiles_client_id ON client_profiles(client_id);
  END IF;
  
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'projects') THEN
    CREATE INDEX IF NOT EXISTS idx_projects_client_id ON projects(client_id);
    CREATE INDEX IF NOT EXISTS idx_projects_freelancer_id ON projects(freelancer_id);
    -- Only create status index if project_status column exists (existing schema)
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'projects' AND column_name = 'project_status') THEN
      CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(project_status);
    END IF;
  END IF;
  
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'transactions') THEN
    CREATE INDEX IF NOT EXISTS idx_transactions_project_id ON transactions(project_id);
    CREATE INDEX IF NOT EXISTS idx_transactions_transaction_id ON transactions(transaction_id);
  END IF;
  
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'messages') THEN
    CREATE INDEX IF NOT EXISTS idx_messages_project_id ON messages(project_id);
    CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at);
  END IF;
END $$;

-- Success message
SELECT 'Database setup completed successfully!' as status; 